name: CodeRabbit PR

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: lovegraph/ai-pr-reviewer-pub@v1-dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
