name: deploy

on:
  push:
    branches:
      - master

env:
  TF_VAR_CODE_HYDEMY_NAME_PROXY: ${{ secrets.CODE_HYDEMY_NAME_PROXY }}
  TF_VAR_SLACK_INCOMING_WEBHOOK_1ST: ${{ secrets.SLACK_INCOMING_WEBHOOK_1ST }}

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.1
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_ARN_GITHUB_ACTIONS_ADMINISTRATOR }}
          aws-region: ap-northeast-1
      - run: terraform init
      - run: terraform apply -auto-approve
      - run: terraform output