name: plan

on:
  push:
    branches-ignore:
      - master


permissions:
  contents: read
  id-token: write

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.1
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_ARN_GITHUB_ACTIONS_ADMINISTRATOR }}
          aws-region: ap-northeast-1
      - run: terraform init
      - run: terraform plan
      - run: terraform output